site_name: LitematicDownloader Documentation
site_url: https://choculaterie.github.io/LitematicDownloader/
repo_url: https://github.com/Choculaterie/LitematicDownloader
repo_name: Choculaterie/LitematicDownloader

nav:
  - LitematicDownloader:
    - Overview: index.md
    - About the Mod: about.md
    - Installation Guide: installation.md
    - Feature Overview: features.md
    - Troubleshooting & Usage Guide: troubleshooting.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
